version: '3.8'

services:
  air-quality-collector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openaq_ingestion_service
    env_file:
      - .env
    volumes:
      - .:/app
      - ~/.config/gcloud:/root/.config/gcloud
    restart: on-failure
    networks:
      - data-pipeline-net

networks:
  data-pipeline-net:
    driver: bridge